### ISSUE TITLE
Incompatible with Traefik 3.1.6?

### ISSUE THREAD

**Issue by skosch** [xzzpig/traefik-oidc-wasm#3]
Thank you so much for sharing this plugin!

It was working great for me with Traefik 3.1.2. Unfortunately 3.1.2 suffered from a nasty memory leak (https://github.com/traefik/traefik/issues/11119), which has been fixed in 3.1.6. However, this plugin doesn't work anymore with 3.1.6; I get an error saying `building Wasm middleware: creating middleware: wasm: guest doesn't export func[handle_request]`. I'm guessing some of the wasm/tinygo dependencies have changed in the meantime, but I ran into some other issues while trying to confirm this (no doubt due to my never having touched Go's build system before).

I would be grateful if you could take a look. Happy to submit a PR as well if you could give me some pointers.

**Comment by xzzpig** [comment]
It seems that Traefik has made changes to the export mechanism of the Wasm plugin in v3.1.3. Please refer to
https://github.com/traefik/traefik/pull/11088

I will fix it as soon as possible

**Comment by xzzpig** [comment]
Fixed in [v0.0.5](https://github.com/xzzpig/traefik-oidc-wasm/releases/tag/v0.0.5)

**Comment by skosch** [comment]
Thank you so much!
